JensTheLandmand_v6/Controllers/ForumController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using JensTheLandmand_v6.Models;
using Microsoft.AspNet.Identity;

namespace JensTheLandmand_v6.Controllers
{
    public class ForumController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Forum   
        [Audit]
        public async Task<ActionResult> Index()
        {
            ViewBag.Message = "Her kan der diskuteres eller stilles spørgsmål omkring landbrug";

            return View(await db.Topics.ToListAsync());
        }

        [HttpGet]
        [Authorize]
        public ActionResult CreateTopic()
        {
            return View();;
        }

        [Audit]
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTopic([Bind(Include = "TopicTitle, TopicNote")] Topics topic)
        {
            if (ModelState.IsValid)
            {
                topic.Creator = User.Identity.GetUserName();

                db.Topics.Add(topic);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        [Audit]
        [HttpGet]
        public ActionResult Comments(int id)
        {
            ViewTopicAndCommentsViewModel view = new ViewTopicAndCommentsViewModel();
            view.topic = db.Topics.FirstOrDefault(x => x.TopicID == id);
            //view.topic = db.Topics.Where(x => x.TopicID == id);

            string currentUserId = User.Identity.GetUserId();
            view.user = db.Users.FirstOrDefault(x => x.Id == currentUserId);

            view.comments = db.Comments.Where(x => x.C_TopicId == id);

            return View(view);
        }

        [HttpGet]
        [Authorize]
        public ActionResult CreateComment(int id)
        {
            return View();
        }

        [Audit]
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateComment(int id, [Bind(Include = "CommentID, Comment")] Comments replyComment)
        {
            if (ModelState.IsValid)
            {
                replyComment.Creator = User.Identity.GetUserName();
                replyComment.C_TopicId = id;

                db.Comments.Add(replyComment);
                await db.SaveChangesAsync();
                return RedirectToAction("Comments", new { id = id});
            }
            return View(replyComment);
        }
        //PRAISE THE SUN \[T]/

        [HttpGet]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> DeleteTopic(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topics topic = await db.Topics.FindAsync(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        [HttpPost, ActionName("DeleteTopic")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Topics topic = db.Topics.Find(id);
            db.Topics.Remove(topic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> EditTopic(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topics topic = await db.Topics.FindAsync(id);

            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> EditTopic(
            [Bind(Include = "TopicID, T_AspNetUserId, TopicTitle, TopicNote, Creator")] Topics topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(topic);
        }
    }
}

JensTheLandmand_v6/Controllers/KontrolPanelController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using JensTheLandmand_v6.Models;

namespace JensTheLandmand_v6.Controllers
{
    [Authorize(Roles = "Security")]
    public class KontrolPanelController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: KontrolPanel
        [HttpGet]
        [Authorize(Roles = "Security")]
        public ActionResult Index()
        {
            return View();
        }

        //Den første piechart
        //Checker hvor ofte index-siderne bliver besøgt
        //Ide: Sæt den så unik IP kun kan klippe på den én gang
        public ActionResult PieChart()
        {
            ChartViewModel view = new ChartViewModel();

            var today = DateTime.Today;
            var date = today.Date;

            view.ForumList =
                db.AuditRecords.Where(
                    r => DbFunctions.TruncateTime(r.TimeAccessed) == date && r.URLAccessed == "/Forum");
            view.LinksList =
                db.AuditRecords.Where(
                    r => DbFunctions.TruncateTime(r.TimeAccessed) == date && r.URLAccessed == "/Links");
            view.ShopList =
                db.AuditRecords.Where(
                    r => DbFunctions.TruncateTime(r.TimeAccessed) == date && r.URLAccessed == "/Shop");

            return View(view);
        }

        //Piechart over besøgt details sider i butik
        public ActionResult DetailsPieChart()
        {
            ChartProductDetailsViewModel newList = new ChartProductDetailsViewModel()
            {
                DetailsList = db.AuditRecords.Where(r => r.URLAccessed.Contains("/Shop/Details/"))
            };

            List<int> intList = new List<int>();

            foreach (var audit in newList.DetailsList)
            {
               //stringList.Add(audit.URLAccessed);
                var number = audit.URLAccessed[audit.URLAccessed.Length - 1];
                int x = (int) char.GetNumericValue(number);
                intList.Add(x);
            }

            List<ChartProducts> chartList = new List<ChartProducts>();
            foreach (var i in intList)
            {
                if (chartList.Any(x => x.id == i) )
                {
                    chartList.First(x => x.id == i).counts++;
                }
                else
                {
                    ChartProducts item = new ChartProducts();
                    item.name = db.Products.First(x => x.ProductID == i).ProductName;
                    item.id = i;
                    item.counts = 1;
                    chartList.Add(item);
                }
            }
            newList.ChartSortedList = chartList;
            return View(newList);
        }

        //Ikke færdig. Listen er taget fra db, men mangler at fjerne dubs
        public ActionResult TotalUnikVisitsChart()
        {
            UnikVisitsViewModel view = new UnikVisitsViewModel();
            var rawIpList = db.AuditRecords.Where(x => x.IPAddress != null);
            List<string> unikIpList = new List<string>();

            foreach (var item in rawIpList)
            {
                if (!unikIpList.Contains(item.IPAddress))
                {
                    unikIpList.Add(item.IPAddress);
                }
                else
                {
                    // \[T]/
                }
            }
            view.IPList = unikIpList;
            return View(view);
        }

        [AllowAnonymous]
        public async Task<ActionResult> DisplayIpActivity()
        {
            var today = DateTime.Today;
            var date = today.Date;

            return View(await db.AuditRecords.Where(x => DbFunctions.TruncateTime(x.TimeAccessed) == date).OrderBy(r => r.IPAddress).ToListAsync());
        }
    }
}

JensTheLandmand_v6/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using JensTheLandmand_v6.Models;

namespace JensTheLandmand_v6.Controllers
{
    public class LinksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Links
        [Audit]
        public async Task<ActionResult> Index()
        {
            ViewBag.Message = "Her er mine foretrukne links";

            return View(await db.Links.ToListAsync());
        }

        [HttpGet]
        [Authorize(Roles = "Security")]
        public ActionResult CreateLink()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> CreateLink([Bind(Include = "LinksID, LinkURL, LinkDesc")] Links link)
        {
            if (ModelState.IsValid)
            {
                db.Links.Add(link);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(link);
        }

        [HttpGet]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> EditLink(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Links link = await db.Links.FindAsync(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> EditLink([Bind(Include = "LinksID, LinkURL, LinkDesc")] Links link)
        {
            if (ModelState.IsValid)
            {
                db.Entry(link).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(link);
        }

        [HttpGet]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> DeleteLink(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Links link = await db.Links.FindAsync(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        [HttpPost, ActionName("DeleteLink")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Links movie = await db.Links.FindAsync(id);
            db.Links.Remove(movie);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

JensTheLandmand_v6/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JensTheLandmand_v6.Models;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.UI.WebControls;

namespace JensTheLandmand_v6.Controllers
{
    public class ShopController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //GET: Shop
        [AllowAnonymous]
        [Audit]
        public async Task<ActionResult> Index()
        {
            var item = await db.Products.ToListAsync();
            var item2 = await db.File.ToListAsync();                      

            ProductViewModel view = new ProductViewModel();
            view.allProducts = item;
            view.AllFiles = item2;

            return View(view);
        }

        public FileContentResult LoadImage(string path)
        {
            byte[] imgArray = System.IO.File.ReadAllBytes(path);
            return new FileContentResult(imgArray, "image/jpg");
        }

        [HttpGet]
        [Authorize(Roles = "Security")]
        public ActionResult CreateProduct()
        {
            return View(new Products());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> CreateProduct([Bind(Include = "ProductName, ProductDesc, ProductPrice")] Products product, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        var avatar = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Avatar,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            avatar.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        product.Files = new List<File> { avatar };
                    }
                    db.Products.Add(product);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(product);
        }

        [HttpGet]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> DeleteProduct(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("DeleteProduct")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Products product = db.Products.Find(id);
            db.Products.Remove(product);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> EditProduct(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Security")]
        public async Task<ActionResult> EditProduct(
            [Bind(Include = "ProductID, ProductName, ProductDesc, ProductPrice")] Products product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [Audit]
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ProductDetails view = new ProductDetails();

            var item3 = db.Products.First(x => x.ProductID == id);
            var item4 = db.File.First(x => x.ProductId == id);

            view.Product = item3;
            view.ImgPath = item4;
            
            return View(view);
        }
    }
}

JensTheLandmand_v6/Views/KontrolPanel/DetailsPieChart.cshtml
@model ChartProductDetailsViewModel

@{
    string[] names = new string[Model.ChartSortedList.Count()];
    int[] counts = new int[Model.ChartSortedList.Count()];
    int counter = 0;
}

@foreach (var item in Model.ChartSortedList)
{
    names[counter] = item.name;
    counts[counter] = item.counts;
    counter++;
}

@{


    var myChart = new Chart(width: 200, height: 200)
        .AddTitle("Vare besøgt i Details i alt")
        .AddSeries(chartType: "Pie",
            name: "Sider",
            xValue: names,
            yValues: counts)
        .Write();
}

JensTheLandmand_v6/Views/KontrolPanel/DisplayIpActivity.cshtml
@model IEnumerable<Audit>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IPAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URLAccessed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeAccessed)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IPAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.URLAccessed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeAccessed)
            </td>

        </tr>
    }

</table>

JensTheLandmand_v6/Views/KontrolPanel/Index.cshtml
@{
    ViewBag.Title = "Kontrol Panel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header page-heading">
    <h2 class="pull-left">@ViewBag.Title</h2>
    <div class="clearfix"></div>
</div>

<h3>Produkter</h3>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Opret Produkt</h4>
            </div>
            <div class="panel-body">
                <p>Opret dine egne vare og tilføj dem til listen</p>
                @Html.ActionLink("Opret", "CreateProduct", "Shop", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Slet Produkt</h4>
            </div>
            <div class="panel-body">
                <p>Slet uønskede produkter fra listen</p>
                @Html.ActionLink("Slet", "Index", "Shop", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Ret Produkt</h4>
            </div>
            <div class="panel-body">
                <p>Ret på produkterne</p>
                @Html.ActionLink("Ret", "Index", "Shop", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
</div>

<h3>Links</h3>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Opret Link</h4>
            </div>
            <div class="panel-body">
                <p>Klik på knappen og opret et product til listen</p>
                @Html.ActionLink("Opret", "CreateLink", "Links", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Slet Link</h4>
            </div>
            <div class="panel-body">
                <p>Klik på knappen og slet et produkt fra listen</p>
                @Html.ActionLink("Slet", "Index", "Links", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Ret Link</h4>
            </div>
            <div class="panel-body">
                <p>Klik på knappen og opret et product til listen</p>
                @Html.ActionLink("Ret", "Index", "Links", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
</div>

<h3>Forum</h3>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Opret Post</h4>
            </div>
            <div class="panel-body">
                <p>Opret et post på Forummet</p>
                @Html.ActionLink("Opret", "CreateTopic", "Forum", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Slet Post</h4>
            </div>
            <div class="panel-body">
                <p>Slet et post på Forummet</p>
                @Html.ActionLink("Slet", "Index", "Forum", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Ret Post</h4>
            </div>
            <div class="panel-body">
                <p>Ret en post på Forummet</p>
                @Html.ActionLink("Ret", "Index", "Forum", null, new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <img src='@Url.Action("PieChart")'/>
    </div>
    <div class="col-md-3">
        <img src='@Url.Action("DetailsPieChart")'/>
    </div>
    <div class="col-md-3">
        <img src='@Url.Action("TotalUnikVisitsChart")'/>
    </div>
</div>

<hr/>
<div class="row">
    @Html.ActionLink("Check bruger aktivitet","DisplayIpActivity","KontrolPanel", null, new {@class ="btn btn-primary"})
</div>

JensTheLandmand_v6/Views/KontrolPanel/PieChart.cshtml
@model ChartViewModel

@{
    var myChart = new Chart(width: 200, height: 200)
        .AddTitle("Besøg i dag")
        .AddSeries(chartType: "Pie",
            name: "Sider",
            xValue: new[] { "Forum", "Links", "Butik" },
            yValues: new[] { Model.ForumList.Count(), Model.LinksList.Count(), Model.ShopList.Count() })
        .Write();
}

JensTheLandmand_v6/Views/KontrolPanel/TotalUnikVisitsChart.cshtml
@model UnikVisitsViewModel

@{
    var myChart = new Chart(width: 200, height: 200)
        .AddTitle("Unik besøg")
        .AddSeries(
            name: "Sider",
            xValue: new[] { "Unik besøgende" },
            yValues: new[] { Model.IPList.Count() })
        .Write();
}